"""Add ScrapingRule model

Revision ID: 13f467930de9
Revises: f38eeb7f9383
Create Date: 2025-12-05 10:55:25.681896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f467930de9'
down_revision = 'f38eeb7f9383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=False, comment='站点名称'),
    sa.Column('domain', sa.String(length=128), nullable=True, comment='站点域名'),
    sa.Column('title_xpath', sa.String(length=256), nullable=True, comment='标题XPath'),
    sa.Column('content_xpath', sa.String(length=256), nullable=True, comment='内容XPath'),
    sa.Column('headers', sa.Text(), nullable=True, comment='Request Headers(JSON)'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraping_rules')
    # ### end Alembic commands ###
