"""Add OpinionData model

Revision ID: 4f7655375f01
Revises: cc1ed6ff739c
Create Date: 2025-12-04 11:05:20.363865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7655375f01'
down_revision = 'cc1ed6ff739c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opinion_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('original_url', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_deep_crawled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraped_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraped_data_keyword'))

    op.drop_table('scraped_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=128), nullable=True),
    sa.Column('title', sa.VARCHAR(length=512), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=128), nullable=True),
    sa.Column('cover', sa.VARCHAR(length=512), nullable=True),
    sa.Column('original_url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('is_deep_scraped', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraped_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraped_data_keyword'), ['keyword'], unique=False)

    op.drop_table('opinion_data')
    op.drop_table('business')
    # ### end Alembic commands ###
