"""Add ScrapedData model

Revision ID: cc1ed6ff739c
Revises: f1fe9f16ec92
Create Date: 2025-12-04 10:21:36.662978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1ed6ff739c'
down_revision = 'f1fe9f16ec92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('cover', sa.String(length=512), nullable=True),
    sa.Column('original_url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_deep_scraped', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraped_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraped_data_keyword'), ['keyword'], unique=False)

    op.drop_table('business')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraped_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraped_data_keyword'))

    op.drop_table('scraped_data')
    # ### end Alembic commands ###
