"""Recreate opinion_detail table

Revision ID: d30284a28f0f
Revises: 4f7655375f01
Create Date: 2025-12-04 22:36:27.057580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30284a28f0f'
down_revision = '4f7655375f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opinion_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opinion_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opinion_id'], ['opinion_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opinion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opinion_detail')
    # ### end Alembic commands ###
